/**
 * SweatSpace.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { AddExerciseRequest } from '../model/addExerciseRequest';
import { ExerciseResponse } from '../model/exerciseResponse';
import { UpdateExerciseRequest } from '../model/updateExerciseRequest';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ExercisesService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param workoutId 
     * @param Shuffle 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getExercises(workoutId: number, Shuffle?: boolean, observe?: 'body', reportProgress?: boolean): Observable<Array<ExerciseResponse>>;
    public getExercises(workoutId: number, Shuffle?: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ExerciseResponse>>>;
    public getExercises(workoutId: number, Shuffle?: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ExerciseResponse>>>;
    public getExercises(workoutId: number, Shuffle?: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (workoutId === null || workoutId === undefined) {
            throw new Error('Required parameter workoutId was null or undefined when calling getExercises.');
        }


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (Shuffle !== undefined && Shuffle !== null) {
            queryParameters = queryParameters.set('Shuffle', <any>Shuffle);
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<ExerciseResponse>>('get',`${this.basePath}/workouts/${encodeURIComponent(String(workoutId))}/Exercises`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param exerciseId 
     * @param workoutId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public workoutsWorkoutIdExercisesExerciseIdDelete(exerciseId: number, workoutId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public workoutsWorkoutIdExercisesExerciseIdDelete(exerciseId: number, workoutId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public workoutsWorkoutIdExercisesExerciseIdDelete(exerciseId: number, workoutId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public workoutsWorkoutIdExercisesExerciseIdDelete(exerciseId: number, workoutId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (exerciseId === null || exerciseId === undefined) {
            throw new Error('Required parameter exerciseId was null or undefined when calling workoutsWorkoutIdExercisesExerciseIdDelete.');
        }

        if (workoutId === null || workoutId === undefined) {
            throw new Error('Required parameter workoutId was null or undefined when calling workoutsWorkoutIdExercisesExerciseIdDelete.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/workouts/${encodeURIComponent(String(workoutId))}/Exercises/${encodeURIComponent(String(exerciseId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Adds a exercise to the specified workout
     * 
     * @param workoutId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public workoutsWorkoutIdExercisesPost(workoutId: number, body?: AddExerciseRequest, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public workoutsWorkoutIdExercisesPost(workoutId: number, body?: AddExerciseRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public workoutsWorkoutIdExercisesPost(workoutId: number, body?: AddExerciseRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public workoutsWorkoutIdExercisesPost(workoutId: number, body?: AddExerciseRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (workoutId === null || workoutId === undefined) {
            throw new Error('Required parameter workoutId was null or undefined when calling workoutsWorkoutIdExercisesPost.');
        }


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/workouts/${encodeURIComponent(String(workoutId))}/Exercises`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param workoutId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public workoutsWorkoutIdExercisesPut(workoutId: string, body?: UpdateExerciseRequest, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public workoutsWorkoutIdExercisesPut(workoutId: string, body?: UpdateExerciseRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public workoutsWorkoutIdExercisesPut(workoutId: string, body?: UpdateExerciseRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public workoutsWorkoutIdExercisesPut(workoutId: string, body?: UpdateExerciseRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (workoutId === null || workoutId === undefined) {
            throw new Error('Required parameter workoutId was null or undefined when calling workoutsWorkoutIdExercisesPut.');
        }


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('put',`${this.basePath}/workouts/${encodeURIComponent(String(workoutId))}/Exercises`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
